services:
  - type: web
    name: harry-potter-db
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_USER
        value: sql12773620
      - key: DB_PASSWORD
        value: W6NSjhvJZp
      - key: DB_NAME
        value: sql12773620
      - key: DB_PORT
        value: 3306
